FROM ubuntu:trusty

ENV VERSION_MONGO_DB 3.0.6

COPY mongod.conf /etc/mongod.conf

RUN \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10 && \
    echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list && \
    apt-get update && \
    apt-get install -y mongodb-org=${VERSION_MONGO_DB} mongodb-org-server=${VERSION_MONGO_DB} mongodb-org-shell=${VERSION_MONGO_DB} mongodb-org-mongos=${VERSION_MONGO_DB} mongodb-org-tools=${VERSION_MONGO_DB}

CMD ["service mongod start"]
