# oasis/ubuntu:0.1
FROM ubuntu:trusty

COPY env/.bash_profile /root/.bash_profile

RUN echo 'Acquire::http { Proxy "http://172.17.42.1:3142"; };' >> /etc/apt/apt.conf.d/01proxy
RUN \
  apt-get update -y && \
  apt-get install -y software-properties-common
